apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: maven-executor
  namespace: testkube
spec:
  executor_type: job
  image: testkube/testkube-maven-executor:latest
  types:
  - maven/project
  - maven/test
  - maven/integration-test
