name: Docker Images for Maven executor
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta*"

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Defaults to JDK 11
      - name: Docker meta for Default Maven executor
        id: meta_maven_executor_default
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/testkube-maven-executor
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

          flavor: |
            latest=auto
            prefix=

      - name: Build Default Maven executor
        uses: docker/bake-action@v1
        with:
          files: |
            build/agent/docker-bake.hcl
            ${{ steps.meta_maven_executor_default.outputs.bake-file }}
          targets: jdk11
          push: true

  alljdks:
    strategy:
      matrix:
        version: [jdk8, jdk11, jdk17, jdk18]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta for Maven executor ${{ matrix.version }}
        id: meta_maven_executor
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/testkube-maven-executor
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
          flavor: |
            latest=auto
            prefix=
            suffix=-${{ matrix.version }}

      - name: Build ${{ matrix.version }} Maven executor
        uses: docker/bake-action@v1
        with:
          files: |
            build/agent/docker-bake.hcl
            ${{ steps.meta_maven_executor.outputs.bake-file }}
          targets: ${{ matrix.version }}
          push: true
